version: 0.2
phases:
  build:
    commands:
      - aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION
      - echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin
      - docker-compose -p flutter_web_firebase_hosting build
      - docker tag flutter_web_firebase_hosting_flutter:latest $CODEBUILD_WEBHOOK_ACTOR_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/flutter_web_firebase_hosting:latest
      - docker push $CODEBUILD_WEBHOOK_ACTOR_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/flutter_web_firebase_hosting_flutter
